# Generated by Django 2.2.9 on 2020-04-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caf', '0002_auto_20200403_1407'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=50)),
                ('enforcement_instrument', models.BooleanField(default=False)),
                ('regulation_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(help_text='Short description of the event', max_length=50)),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('document_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('response_date_requested', models.DateField(blank=True, null=True)),
                ('response_received', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('participants', models.ManyToManyField(to='organisations.Person')),
                ('related_caf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caf.CAF')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.EngagementType')),
            ],
        ),
    ]
