# Generated by Django 3.1.2 on 2020-10-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAFSingleDateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('short_description', models.CharField(help_text='Short description of the event. Use Comments field for full detail.', max_length=50)),
                ('document_link', models.URLField(blank=True, help_text='Use this to link to documents on TiME/Sharepoint or elsewhere.', max_length=1000, null=True)),
                ('comments', models.TextField(blank=True, help_text='Use this to provide further detail about the event.', max_length=1000, null=True)),
                ('date', models.DateField(help_text='DD/MM/YY format')),
                ('type_descriptor', models.CharField(choices=[('CAF_INITIAL_CAF_RECEIVED', 'CAF - Initial CAF Received'), ('CAF_FEEDBACK_EMAILED_OES', 'CAF - Emailed to OES'), ('CAF_RECEIVED', 'CAF - Received'), ('CAF_EMAILED_ROSA', 'CAF - Emailed to Rosa'), ('CAF_VALIDATION_SIGN_OFF', 'CAF - Validation Sign Off'), ('CAF_VALIDATION_RECORD_EMAILED_TO_OES', 'CAF - Validation Record Sent to OES')], help_text='Select the event type', max_length=50, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='CAFTwinDateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('short_description', models.CharField(help_text='Short description of the event. Use Comments field for full detail.', max_length=50)),
                ('document_link', models.URLField(blank=True, help_text='Use this to link to documents on TiME/Sharepoint or elsewhere.', max_length=1000, null=True)),
                ('comments', models.TextField(blank=True, help_text='Use this to provide further detail about the event.', max_length=1000, null=True)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type_descriptor', models.CharField(choices=[('CAF_PEER_REVIEW_PERIOD', 'CAF - Peer Review Period'), ('CAF_VALIDATION_PERIOD', 'CAF - Validation Period')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(help_text='Short description of the event. Use Comments field for full detail.', max_length=50)),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, help_text='Should be used for periodic events.', null=True)),
                ('document_link', models.URLField(blank=True, help_text='URL only - do not try to drag a file here.', max_length=1000, null=True)),
                ('response_date_requested', models.DateField(blank=True, null=True)),
                ('response_received', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Use this to provide further detail about the event.', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=100)),
                ('enforcement_instrument', models.BooleanField(default=False)),
                ('regulation_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('single_date_type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('short_description', models.CharField(help_text='Short description of the event. Use Comments field for full detail.', max_length=50)),
                ('document_link', models.URLField(blank=True, help_text='Use this to link to documents on TiME/Sharepoint or elsewhere.', max_length=1000, null=True)),
                ('comments', models.TextField(blank=True, help_text='Use this to provide further detail about the event.', max_length=1000, null=True)),
                ('url', models.URLField(blank=True, help_text='If recording an email, please link to it here. Do not paste the text in the comments box.', max_length=400, null=True, verbose_name='URL')),
                ('requested_response_date', models.DateField(blank=True, help_text='DD/MM/YY format', null=True)),
                ('response_received_date', models.DateField(blank=True, help_text='DD/MM/YY format', null=True)),
                ('private', models.BooleanField(default=False, help_text='Private events can only be seen by you. Official records should not be private, but you can use private events to track your own work.')),
                ('type_descriptor', models.CharField(default='NOTE', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleDateTimeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('short_description', models.CharField(help_text='Short description of the event. Use Comments field for full detail.', max_length=50)),
                ('document_link', models.URLField(blank=True, help_text='Use this to link to documents on TiME/Sharepoint or elsewhere.', max_length=1000, null=True)),
                ('comments', models.TextField(blank=True, help_text='Use this to provide further detail about the event.', max_length=1000, null=True)),
                ('location', models.CharField(blank=True, help_text='If event involved a physical location, indicate here.', max_length=100)),
                ('url', models.URLField(blank=True, help_text='If recording an email, please link to it here. Do not paste the text in the comments box.', max_length=400, null=True, verbose_name='URL')),
                ('date', models.DateTimeField(help_text='DD/MM/YY HH:MM format please!', verbose_name='Date/Time')),
                ('requested_response_date', models.DateField(blank=True, help_text='DD/MM/YY format', null=True)),
                ('response_received_date', models.DateField(blank=True, help_text='DD/MM/YY format', null=True)),
                ('private', models.BooleanField(default=False, help_text='Private events can only be seen by you. Official records should not be private, but you can use private events to track your own work.')),
                ('type_descriptor', models.CharField(choices=[('MEETING', 'Meeting'), ('PHONE_CALL', 'Phone Call'), ('VIDEO_CALL', 'Video Call'), ('EMAIL', 'Email')], max_length=50, verbose_name='Event Type')),
                ('participants', models.ManyToManyField(to='organisations.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
