# Generated by Django 2.2.9 on 2020-02-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='document_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='related_caf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caf.CAF'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='response_date_requested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='response_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementtype',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='engagementtype',
            name='regulation_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
