# Generated by Django 2.2.12 on 2020-10-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_engagementevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='comments',
            field=models.TextField(blank=True, help_text='Use this to provide further detail about the event.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='document_link',
            field=models.URLField(blank=True, help_text='URL only - do not try to drag a file here', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='organisations.Person'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='related_caf',
            field=models.ForeignKey(blank=True, help_text='If the event relates to a CAF, refer to it here.', null=True, on_delete=django.db.models.deletion.CASCADE, to='caf.CAF'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='short_description',
            field=models.CharField(help_text='Short description of the event. Use Comments field for full detail.', max_length=50),
        ),
    ]
