# Generated by Django 3.1.2 on 2020-10-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20201015_1955'),
        ('register', '0002_auto_20201014_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singledatetimeevent',
            name='participants',
            field=models.ManyToManyField(blank=True, to='organisations.Person'),
        ),
    ]
