# Generated by Django 2.2.9 on 2020-02-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200221_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementevent',
            name='short_description',
            field=models.CharField(default='NA', help_text='Short description of the event', max_length=50),
            preserve_default=False,
        ),
    ]
