# Generated by Django 2.2.9 on 2020-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_engagementevent_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementevent',
            name='comments',
            field=models.TextField(default='No comment', max_length=1000),
            preserve_default=False,
        ),
    ]
