# Generated by Django 2.2.12 on 2020-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201001_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='document_link',
            field=models.URLField(blank=True, help_text='URL only - do not try to drag a file here.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Should be used for periodic events.', null=True),
        ),
        migrations.AlterField(
            model_name='engagementtype',
            name='descriptor',
            field=models.CharField(max_length=100),
        ),
    ]
