# Generated by Django 3.1.2 on 2020-10-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201015_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='singledatetimeevent',
            name='private',
            field=models.BooleanField(default=False, help_text='Private events can only be seen by you. Official records should not be private, but you can use private events to track your own work.'),
        ),
        migrations.AddField(
            model_name='singledatetimeevent',
            name='url',
            field=models.URLField(blank=True, help_text='If recording an email, please link to it here. Do not paste the text in the comments box.', max_length=400, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='singledatetimeevent',
            name='location',
            field=models.CharField(blank=True, help_text='If event involved a physical location, indicate here.', max_length=100),
        ),
        migrations.AlterField(
            model_name='singledatetimeevent',
            name='type_descriptor',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('PHONE_CALL', 'Phone Call'), ('VIDEO_CALL', 'Video Call'), ('EMAIL', 'Email'), ('NOTE', 'Note')], max_length=50),
        ),
    ]
