# Generated by Django 2.2.9 on 2020-03-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_engagementevent_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
