# Generated by Django 2.2.12 on 2020-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20201002_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='participants',
            field=models.ManyToManyField(blank=True, to='organisations.Person'),
        ),
    ]
