# Generated by Django 2.2.12 on 2020-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20201002_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementtype',
            name='single_date_type',
            field=models.BooleanField(default=False),
        ),
    ]
