# Generated by Django 3.1.2 on 2020-10-19 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20201015_1955'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0005_auto_20201019_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singledatetimeevent',
            name='type_descriptor',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('PHONE_CALL', 'Phone Call'), ('VIDEO_CALL', 'Video Call'), ('EMAIL', 'Email')], max_length=50, verbose_name='Event Type'),
        ),
        migrations.CreateModel(
            name='NoteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('short_description', models.CharField(help_text='Short description of the event. Use Comments field for full detail.', max_length=50)),
                ('document_link', models.URLField(blank=True, help_text='URL only - do not try to drag a file here.', max_length=1000, null=True)),
                ('comments', models.TextField(blank=True, help_text='Use this to provide further detail about the event.', max_length=1000, null=True)),
                ('url', models.URLField(blank=True, help_text='If recording an email, please link to it here. Do not paste the text in the comments box.', max_length=400, null=True, verbose_name='URL')),
                ('requested_response_date', models.DateField(blank=True, help_text='DD/MM/YY format', null=True)),
                ('response_received_date', models.DateField(blank=True, help_text='DD/MM/YY format', null=True)),
                ('private', models.BooleanField(default=False, help_text='Private events can only be seen by you. Official records should not be private, but you can use private events to track your own work.')),
                ('type_descriptor', models.CharField(default='NOTE', max_length=50)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
