TRUNCATE TABLE users_user RESTART IDENTITY CASCADE;
TRUNCATE TABLE organisations_organisation RESTART IDENTITY CASCADE;
TRUNCATE TABLE organisations_mode RESTART IDENTITY CASCADE;
TRUNCATE TABLE organisations_role RESTART IDENTITY CASCADE;
TRUNCATE TABLE organisations_address RESTART IDENTITY CASCADE;
TRUNCATE TABLE organisations_addresstype RESTART IDENTITY CASCADE;
