# Generated by Django 2.2.9 on 2020-01-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0014_auto_20200125_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAFFileStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=100)),
                ('virtual_location', models.CharField(help_text='USB, Rosa, email, etc', max_length=100)),
                ('physical_location', models.CharField(blank=True, help_text='Cupboard, room, building, etc', max_length=100)),
                ('physical_location_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
            ],
            options={
                'verbose_name': 'CAF File Store',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Triage'), (2, 'First Assessment')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Excel'), (2, 'Word'), (3, 'PDF'), (4, 'Hard Copy')], default=1)),
                ('file_store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.CAFFileStore')),
            ],
        ),
        migrations.CreateModel(
            name='CAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essential_system', models.CharField(blank=True, max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.DocumentFile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('triage_ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.Ranking')),
            ],
            options={
                'verbose_name': 'CAF',
            },
        ),
    ]
