# Generated by Django 2.2.9 on 2020-04-03 14:07

import ctrack.caf.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caf', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestore',
            name='physical_location_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='file_store_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.FileStore'),
        ),
        migrations.AddField(
            model_name='caf',
            name='confidence_grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confidence_grading', to='caf.Grading'),
        ),
        migrations.AddField(
            model_name='caf',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caf.DocumentFile'),
        ),
        migrations.AddField(
            model_name='caf',
            name='quality_grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_grading', to='caf.Grading'),
        ),
        migrations.AddField(
            model_name='caf',
            name='triage_review_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Person'),
        ),
        migrations.AddField(
            model_name='applicablesystem',
            name='caf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicable_systems', to='caf.CAF'),
        ),
        migrations.AddField(
            model_name='applicablesystem',
            name='organisation',
            field=models.ForeignKey(on_delete=models.SET(ctrack.caf.models.ApplicableSystem.get_sentinel_org), to='organisations.Organisation'),
        ),
    ]
