# Generated by Django 2.2.9 on 2020-02-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caf', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffilestore',
            name='physical_location_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='caf',
            name='file',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='caf.DocumentFile'),
        ),
        migrations.AddField(
            model_name='caf',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='caf',
            name='triage_ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.Ranking'),
        ),
    ]
