# Generated by Django 2.2.12 on 2020-08-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caf',
            name='systems',
            field=models.ManyToManyField(to='caf.ApplicableSystem'),
        ),
    ]
