# Generated by Django 3.1.2 on 2020-10-21 15:51

import ctrack.caf.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caf', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestore',
            name='physical_location_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='essentialservice',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='essentialservice',
            name='systems',
            field=models.ManyToManyField(to='caf.ApplicableSystem'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='file_store_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.filestore'),
        ),
        migrations.AddField(
            model_name='caf',
            name='confidence_grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confidence_grading', to='caf.grading'),
        ),
        migrations.AddField(
            model_name='caf',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caf.documentfile'),
        ),
        migrations.AddField(
            model_name='caf',
            name='organisation',
            field=models.ForeignKey(on_delete=models.SET(ctrack.caf.models.CAF.get_sentinel_org), to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='caf',
            name='quality_grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_grading', to='caf.grading'),
        ),
        migrations.AddField(
            model_name='caf',
            name='systems',
            field=models.ManyToManyField(to='caf.ApplicableSystem'),
        ),
        migrations.AddField(
            model_name='caf',
            name='triage_review_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.person'),
        ),
    ]
