# Generated by Django 2.2.9 on 2020-02-21 21:04

import ctrack.caf.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200220_1634'),
        ('caf', '0002_auto_20200220_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caf',
            name='essential_system',
        ),
        migrations.CreateModel(
            name='EssentialService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1000)),
                ('caf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.CAF')),
                ('organisation', models.ForeignKey(on_delete=models.SET(ctrack.caf.models.EssentialService.get_sentinel_org), to='organisations.Organisation')),
            ],
            options={
                'verbose_name': 'Essential Service',
            },
        ),
    ]
