# Generated by Django 2.2.9 on 2020-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0002_auto_20200403_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicablesystem',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
