# Generated by Django 2.2.9 on 2020-02-21 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0003_auto_20200221_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caf',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caf.DocumentFile'),
        ),
        migrations.AlterField(
            model_name='caf',
            name='triage_ranking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caf.Ranking'),
        ),
    ]
