# Generated by Django 2.2.12 on 2020-08-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0003_auto_20200424_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicablesystem',
            options={'verbose_name': 'NIS System'},
        ),
        migrations.RemoveField(
            model_name='applicablesystem',
            name='description',
        ),
        migrations.AddField(
            model_name='applicablesystem',
            name='function',
            field=models.TextField(blank=True, help_text='How the system is relevant to delivering or supporting the essential service', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='applicablesystem',
            name='name',
            field=models.CharField(help_text='System name assigned by OES', max_length=256),
        ),
    ]
