# Generated by Django 2.2.9 on 2020-02-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0004_auto_20200221_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('type', models.IntegerField(choices=[(1, 'Good'), (2, 'Bad'), (3, 'OK')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='description',
            field=models.TextField(default='NA', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ranking',
            name='type',
            field=models.IntegerField(choices=[(1, 'Triage'), (2, 'First Assessment'), (3, 'Validation')], default=1),
        ),
        migrations.AddField(
            model_name='caf',
            name='confidence_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caf.ConfidenceAssessment'),
        ),
    ]
