# Generated by Django 2.2.9 on 2020-02-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0005_auto_20200221_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confidenceassessment',
            name='type',
        ),
        migrations.AlterField(
            model_name='confidenceassessment',
            name='descriptor',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Bad'), (3, 'OK')], default=1),
        ),
    ]
