# Generated by Django 2.2.12 on 2020-08-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0005_applicablesystem_oes_categorisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicablesystem',
            name='oes_categorisation',
        ),
        migrations.AddField(
            model_name='applicablesystem',
            name='dft_categorisation',
            field=models.CharField(choices=[('CR', 'Critical'), ('IM', 'Important')], default='CR', help_text='Refer to documentation for description of these criteria', max_length=2, verbose_name='DfT Categorisation'),
        ),
    ]
