# Generated by Django 2.2.9 on 2020-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0006_auto_20200221_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidenceassessment',
            name='descriptor',
            field=models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad'), ('OK', 'OK')], default=1, max_length=10),
        ),
    ]
