# Generated by Django 2.2.12 on 2020-08-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0007_auto_20200814_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicablesystem',
            name='essential_service',
            field=models.CharField(default='NA', help_text='Name of the essential service which the system suppports.', max_length=255, verbose_name='Essential Service'),
        ),
        migrations.AlterField(
            model_name='applicablesystem',
            name='oes_categorisation',
            field=models.CharField(default='NA', help_text="Categorisation based on OES' own internal prioritisation process.", max_length=255, verbose_name='OES Categorisation'),
        ),
    ]
