# Generated by Django 2.2.9 on 2020-02-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0007_auto_20200221_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=2)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='caf',
            name='confidence_assessment',
        ),
        migrations.RemoveField(
            model_name='caf',
            name='triage_ranking',
        ),
        migrations.DeleteModel(
            name='ConfidenceAssessment',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
        migrations.AddField(
            model_name='caf',
            name='confidence_grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confidence_grading', to='caf.Grading'),
        ),
        migrations.AddField(
            model_name='caf',
            name='triage_grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triage_grading', to='caf.Grading'),
        ),
    ]
