# Generated by Django 2.2.9 on 2020-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0008_auto_20200225_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='type',
            field=models.CharField(choices=[('CONFIDENCE', 'Confidence'), ('QUALITY', 'Quality'), ('MISC', 'Misc')], default='MISC', help_text='Type of grading', max_length=20),
            preserve_default=False,
        ),
    ]
