# Generated by Django 2.2.12 on 2020-08-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_auto_20200531_1441'),
        ('caf', '0008_auto_20200814_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicablesystem',
            name='essential_service',
            field=models.CharField(default='NA', help_text='Description of the essential service which the system suppports.', max_length=255, verbose_name='Essential Service'),
        ),
        migrations.CreateModel(
            name='EssentialService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('systems', models.ManyToManyField(to='caf.ApplicableSystem')),
            ],
        ),
    ]
