# Generated by Django 2.2.9 on 2020-02-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0009_grading_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='descriptor',
            field=models.CharField(help_text='Q1, C1, etc', max_length=2),
        ),
    ]
