# Generated by Django 2.2.9 on 2020-02-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0010_auto_20200225_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caf',
            name='triage_grading',
        ),
        migrations.AddField(
            model_name='caf',
            name='quality_grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_grading', to='caf.Grading'),
        ),
    ]
