# Generated by Django 2.2.9 on 2020-02-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0011_auto_20200225_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caffilestore',
            options={},
        ),
    ]
