# Generated by Django 2.2.9 on 2020-02-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200220_1634'),
        ('caf', '0012_auto_20200226_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CAFFileStore',
            new_name='FileStore',
        ),
    ]
