# Generated by Django 2.2.9 on 2020-03-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0014_auto_20200228_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialservice',
            name='caf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essential_services', to='caf.CAF'),
        ),
    ]
