# Generated by Django 2.2.9 on 2020-03-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200303_0727'),
        ('caf', '0015_auto_20200303_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='caf',
            name='comments',
            field=models.TextField(default='No comment', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caf',
            name='triage_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caf',
            name='triage_review_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Person'),
        ),
        migrations.AddField(
            model_name='caf',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
