# Generated by Django 2.2.9 on 2020-03-04 19:25

import ctrack.caf.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200303_0727'),
        ('caf', '0016_auto_20200303_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicableSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1000)),
                ('caf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicable_systems', to='caf.CAF')),
                ('organisation', models.ForeignKey(on_delete=models.SET(ctrack.caf.models.ApplicableSystem.get_sentinel_org), to='organisations.Organisation')),
            ],
            options={
                'verbose_name': 'Applicable System',
            },
        ),
        migrations.DeleteModel(
            name='EssentialService',
        ),
    ]
