# Generated by Django 2.2.9 on 2020-03-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caf', '0017_auto_20200304_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caf',
            name='owner',
        ),
    ]
