# Generated by Django 2.2.9 on 2020-04-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAFAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'CAF Assessment',
            },
        ),
        migrations.CreateModel(
            name='CAFObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Managing Risk', max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('order_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'CAF Objective',
            },
        ),
        migrations.CreateModel(
            name='CAFPrinciple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='e.g. A1, B3, etc', max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('order_id', models.IntegerField()),
                ('caf_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.CAFObjective')),
            ],
            options={
                'verbose_name': 'CAF Principle',
            },
        ),
        migrations.CreateModel(
            name='CAFContributingOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='e.g. A1.a, B3.c, etc', max_length=5)),
                ('name', models.CharField(help_text='e.g. Board Direction', max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('order_id', models.IntegerField()),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.CAFPrinciple')),
            ],
            options={
                'verbose_name': 'CAF Contributing Outcome',
            },
        ),
        migrations.CreateModel(
            name='CAFAssessmentOutcomeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_score', models.CharField(choices=[('Achieved', 'Achieved'), ('Partially Achieved', 'Partially Achieved'), ('Not Achieved', 'Not Achieved')], help_text='Choose an assessment score', max_length=20, verbose_name='Assessment Score')),
                ('baseline_assessment_score', models.CharField(choices=[('Achieved', 'Achieved'), ('Partially Achieved', 'Partially Achieved'), ('Not Achieved', 'Not Achieved')], help_text='Choose an assessment score', max_length=20, verbose_name='Baseline Score')),
                ('caf_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.CAFAssessment', verbose_name='CAF Assessment')),
                ('caf_contributing_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.CAFContributingOutcome', verbose_name='CAF Contributing Outcome')),
            ],
            options={
                'verbose_name': 'CAF Assessment Outcome Score',
            },
        ),
    ]
