# Generated by Django 2.2.9 on 2020-03-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0006_organisation_oes'),
        ('caf', '0018_remove_caf_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAFContributingOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='e.g. A1.a, B3.c, etc', max_length=5)),
                ('descriptor', models.CharField(help_text='e.g. Board Direction', max_length=50)),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CAFObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Managing Risk', max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CAFSelfAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=500)),
                ('caf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.CAF')),
                ('completer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Person')),
            ],
        ),
        migrations.CreateModel(
            name='CAFSelfAssessmentOutcomeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caf_contributing_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.CAFContributingOutcome')),
                ('caf_self_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.CAFSelfAssessment')),
            ],
        ),
        migrations.CreateModel(
            name='CAFPrinciple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='e.g. A1, B3, etc', max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('order_id', models.IntegerField()),
                ('caf_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.CAFObjective')),
            ],
        ),
        migrations.AddField(
            model_name='cafcontributingoutcome',
            name='principle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.CAFPrinciple'),
        ),
    ]
