# Generated by Django 2.2.9 on 2020-04-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('caf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafassessment',
            name='caf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.CAF'),
        ),
    ]
