# Generated by Django 3.1.2 on 2020-10-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caf', '0001_initial'),
        ('assessments', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafassessment',
            name='caf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caf.caf'),
        ),
        migrations.AddField(
            model_name='cafassessment',
            name='completer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.person'),
        ),
    ]
