# Generated by Django 2.2.9 on 2020-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafcontributingoutcome',
            options={'verbose_name': 'CAF Contributing Outcome'},
        ),
        migrations.AlterModelOptions(
            name='cafobjective',
            options={'verbose_name': 'CAF Objective'},
        ),
        migrations.AlterModelOptions(
            name='cafprinciple',
            options={'verbose_name': 'CAF Principle'},
        ),
        migrations.AlterModelOptions(
            name='cafselfassessment',
            options={'verbose_name': 'CAF Self Assessment'},
        ),
        migrations.AlterModelOptions(
            name='cafselfassessmentoutcomescore',
            options={'verbose_name': 'CAF Self Assessment Outcome Score'},
        ),
        migrations.AlterField(
            model_name='cafobjective',
            name='name',
            field=models.CharField(help_text='e.g. Managing Risk', max_length=100),
        ),
    ]
