# Generated by Django 2.2.9 on 2020-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20200315_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafcontributingoutcome',
            old_name='descriptor',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cafcontributingoutcome',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
