# Generated by Django 3.1.2 on 2020-10-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_cafassessment_caf'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafassessment',
            name='completer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.person'),
        ),
    ]
