# Generated by Django 2.2.9 on 2020-04-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('assessments', '0002_cafassessment_caf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafassessment',
            name='completer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Person'),
        ),
    ]
