# Generated by Django 3.0.5 on 2020-05-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_cafassessment_completer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=50)),
                ('color_description', models.CharField(max_length=100)),
                ('color_hex', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='IGP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive_text', models.CharField(max_length=2000)),
                ('achievement_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.AchievementLevel')),
                ('contributing_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.CAFContributingOutcome')),
            ],
        ),
    ]
