# Generated by Django 3.0.5 on 2020-05-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_achievementlevel_igp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igp',
            options={'verbose_name': 'IGP'},
        ),
        migrations.RenameField(
            model_name='achievementlevel',
            old_name='color_description',
            new_name='colour_description',
        ),
        migrations.RenameField(
            model_name='achievementlevel',
            old_name='color_hex',
            new_name='colour_hex',
        ),
    ]
