# Generated by Django 2.2.9 on 2020-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20200315_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafselfassessmentoutcomescore',
            name='baseline_assessment_score',
            field=models.CharField(choices=[('Achieved', 'Achieved'), ('Partially Achieved', 'Partially Achieved'), ('Not Achieved', 'Not Achieved')], default='Achieved', help_text='Choose an assessment score', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafselfassessmentoutcomescore',
            name='self_assessment_score',
            field=models.CharField(choices=[('Achieved', 'Achieved'), ('Partially Achieved', 'Partially Achieved'), ('Not Achieved', 'Not Achieved')], default='Achieved', help_text='Choose an assessment score', max_length=20),
            preserve_default=False,
        ),
    ]
