# Generated by Django 2.2.9 on 2020-04-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200403_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
