# Generated by Django 2.2.9 on 2020-02-20 16:25

import ctrack.organisations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200220_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='updated_by',
            field=models.ForeignKey(on_delete=models.SET(ctrack.organisations.models.Organisation.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
