# Generated by Django 3.0.5 on 2020-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20200424_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='oes',
            field=models.BooleanField(default=True),
        ),
    ]
