# Generated by Django 2.2.9 on 2020-02-20 16:34

import ctrack.organisations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20200220_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='updated_by',
            field=models.ForeignKey(on_delete=models.SET(ctrack.organisations.models.Person.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
