# Generated by Django 2.2.9 on 2020-03-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200220_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='designation_type',
            field=models.IntegerField(choices=[(1, 'Automatic'), (2, 'Reserve Power'), (3, 'NA')], default=1),
        ),
    ]
