# Generated by Django 2.2.9 on 2020-01-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200121_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisations.AddressType'),
        ),
    ]
