# Generated by Django 3.0.5 on 2020-05-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200513_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Person')),
            ],
        ),
    ]
