# Generated by Django 2.2.9 on 2020-03-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200303_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='oes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
