# Generated by Django 2.2.9 on 2020-01-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200121_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
            preserve_default=False,
        ),
    ]
