# Generated by Django 2.2.12 on 2020-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20200529_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='date_time_incident_detected',
            field=models.DateTimeField(verbose_name='Date/Time incident detected'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='dft_handle_status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('REVIEWING', 'REVIEWING'), ('WAITING', 'WAITING'), ('COMPLETED', 'COMPLETED')], default='QUEUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_stage',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Ended', 'Ended'), ('Ongoing but managed', 'Ongoing but managed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_status',
            field=models.CharField(choices=[('Detected', 'Detected'), ('Suspected', 'Suspected'), ('Resolved', 'Resolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('Cyber', 'Cyber'), ('Non-Cyber', 'Non-Cyber'), ('Both', 'Both'), ('Power Outage', 'Power Outage')], help_text='This can be appoximate', max_length=20),
        ),
    ]
