# Generated by Django 2.2.9 on 2020-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_auto_20200124_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='landline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
