# Generated by Django 2.2.12 on 2020-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_incidentreport_person_involved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='role',
            field=models.CharField(blank=True, help_text='Role of person reporting/detecting incident', max_length=100),
        ),
    ]
