# Generated by Django 2.2.12 on 2020-05-31 14:41

import django.contrib.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_auto_20200529_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='reporting_person',
            field=models.ForeignKey(on_delete=models.SET(django.contrib.auth.get_user_model), to='organisations.Person', verbose_name='Person reporting the incident'),
        ),
    ]
