# Generated by Django 2.2.9 on 2020-01-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_mode_submode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='submode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisations.Submode'),
            preserve_default=False,
        ),
    ]
