# Generated by Django 2.2.9 on 2020-02-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0014_auto_20200125_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='designation_type',
            field=models.IntegerField(choices=[(1, 'Automatic'), (2, 'Reserve Power')], default=1),
        ),
    ]
