# Generated by Django 2.2.9 on 2020-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0015_organisation_designation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='registered_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='registered_company_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
