# Generated by Django 2.2.9 on 2020-02-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0017_auto_20200217_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='comments',
            field=models.TextField(default='NA', max_length=500),
            preserve_default=False,
        ),
    ]
