# Generated by Django 2.2.9 on 2020-02-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0018_organisation_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
