# Generated by Django 2.2.9 on 2020-02-17 21:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0019_organisation_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='clearance',
            field=models.IntegerField(choices=[(1, 'NA'), (2, 'BPSS'), (3, 'CTC'), (4, 'SC'), (5, 'DV'), (6, 'Other')], default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='clearance_expiry',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 17, 21, 22, 59, 545682)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='clearance_last_checked',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 17, 21, 23, 6, 797385)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='clearance_sponsor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='organisations.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='clearance_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 17, 21, 23, 40, 808513)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='comments',
            field=models.TextField(default='NA', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='date_ended',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 17, 21, 23, 53, 114873)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Malcolm', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='has_egress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='job_title',
            field=models.CharField(default='Firestarter', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Holis-Grander', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='predecessor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='previous_person', to='organisations.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='primary_nis_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.IntegerField(choices=[(1, 'Mr'), (2, 'Mrs'), (3, 'Miss'), (4, 'Ms'), (5, 'Dr.'), (6, 'Professor'), (7, 'The Rt Hon.'), (8, 'Lord'), (9, 'Lady')], default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='voluntary_point_of_contact',
            field=models.BooleanField(default=False),
        ),
    ]
