# Generated by Django 2.2.9 on 2020-02-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0020_auto_20200217_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='clearance_sponsor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='has_egress',
            field=models.BooleanField(default=False, verbose_name='Has Egress'),
        ),
        migrations.AlterField(
            model_name='person',
            name='primary_nis_contact',
            field=models.BooleanField(default=False, verbose_name='Primary NIS contact'),
        ),
    ]
